"""Privacy-bounded per-session M18 qualification receipts.

A receipt is derived once, from one completed runtime session's own
`laconic.ledger.Ledger` (opened through `laconic.runtime.storage.RuntimeStorage`,
never a second raw store), plus a handful of operator attestations the
ledger itself cannot record: whether OMP reached a clean `session_shutdown`,
the wall-clock session bounds, which M18 scenarios this session exercised,
and any result corruption the operator observed at the OMP boundary. It
reads raw observation text only in memory, to verify byte-exact recovery,
and never serializes a raw observation, subject, tool argument, path, or
the real session ID -- only counts, character totals, latencies, and hashes
derived from them.
"""

from __future__ import annotations

import hashlib
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from laconic.beta.canon import canonical_sha256
from laconic.beta.manifest import CampaignManifest, fingerprint_manifest
from laconic.beta.scenarios import ALL_SCENARIOS
from laconic.ledger import InvalidSpanError, UnknownHandleError
from laconic.runtime.references import InvalidRuntimeReferenceError, RuntimeReference
from laconic.runtime.storage import RuntimeStorage

#: Bumped whenever a receipt field is added, removed, or reinterpreted.
RECEIPT_SCHEMA_VERSION = 1

#: The only reason the runtime engine (`laconic.runtime.engine`) ever
#: records for an emitted decision.
KNOWN_EMITTED_REASON = "smaller_envelope"

#: The complete, closed set of pass-through reasons the runtime engine
#: (`laconic.runtime.engine._pass_through` call sites) can record. A reason
#: outside this set means either engine.py grew a new pass-through path
#: this contract has not reviewed, or the ledger row was tampered with --
#: both fail receipt derivation rather than silently widening the allowlist.
KNOWN_PASS_THROUGH_REASONS = frozenset(
    {"unsupported_tool", "tool_error", "recovery_mismatch", "not_smaller"}
)

KNOWN_REASONS = KNOWN_PASS_THROUGH_REASONS | {KNOWN_EMITTED_REASON}

#: The exact key set a serialized receipt may ever contain.
ALLOWED_RECEIPT_KEYS = frozenset(
    {
        "schema_version",
        "schema_hash",
        "manifest_hash",
        "candidate_wheel_sha256",
        "slot",
        "repository_id",
        "clean_shutdown",
        "started_at",
        "ended_at",
        "scenarios",
        "decisions_total",
        "eligible_observations",
        "emitted_count",
        "pass_through_counts",
        "raw_chars",
        "visible_chars",
        "characters_avoided",
        "full_expansions",
        "span_expansions",
        "latencies_ms",
        "exact_expansion_failures",
        "compressed_tool_errors",
        "oversized_envelopes",
        "observed_corruption",
    }
)


class ReceiptDerivationError(ValueError):
    """Raised when a session ledger cannot yield a valid M18 receipt."""


class ReceiptFormatError(ValueError):
    """Raised when a serialized receipt is internally inconsistent.

    Distinct from :class:`ReceiptDerivationError`: this fires later, when
    reconstructing a typed receipt from a JSON payload that already cleared
    the exact-key/enum privacy gate but does not arithmetically add up --
    the signature of hand-edited ("mutated") evidence.
    """


def receipt_schema_fingerprint() -> str:
    """Return the canonical SHA-256 of the receipt contract this build
    understands: its field set and closed reason/scenario vocabularies.

    Bound into every receipt so a report generated by a later build whose
    contract has silently drifted -- a field renamed, a reason retired --
    can tell a receipt captured under the old contract is stale, not just
    superficially well-formed JSON.
    """
    return canonical_sha256(
        {
            "schema_version": RECEIPT_SCHEMA_VERSION,
            "keys": sorted(ALLOWED_RECEIPT_KEYS),
            "known_reasons": sorted(KNOWN_REASONS),
            "known_scenarios": sorted(ALL_SCENARIOS),
        }
    )


@dataclass(frozen=True, slots=True)
class SessionReceipt:
    """One session's content-free qualification evidence."""

    schema_version: int
    schema_hash: str
    manifest_hash: str
    candidate_wheel_sha256: str
    slot: int
    repository_id: str
    clean_shutdown: bool
    started_at: float
    ended_at: float
    scenarios: tuple[str, ...]
    decisions_total: int
    eligible_observations: int
    emitted_count: int
    pass_through_counts: tuple[tuple[str, int], ...]
    raw_chars: int
    visible_chars: int
    characters_avoided: int
    full_expansions: int
    span_expansions: int
    latencies_ms: tuple[float, ...]
    exact_expansion_failures: int
    compressed_tool_errors: int
    oversized_envelopes: int
    observed_corruption: int

    def to_json(self) -> dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "schema_hash": self.schema_hash,
            "manifest_hash": self.manifest_hash,
            "candidate_wheel_sha256": self.candidate_wheel_sha256,
            "slot": self.slot,
            "repository_id": self.repository_id,
            "clean_shutdown": self.clean_shutdown,
            "started_at": self.started_at,
            "ended_at": self.ended_at,
            "scenarios": sorted(self.scenarios),
            "decisions_total": self.decisions_total,
            "eligible_observations": self.eligible_observations,
            "emitted_count": self.emitted_count,
            "pass_through_counts": [list(item) for item in self.pass_through_counts],
            "raw_chars": self.raw_chars,
            "visible_chars": self.visible_chars,
            "characters_avoided": self.characters_avoided,
            "full_expansions": self.full_expansions,
            "span_expansions": self.span_expansions,
            "latencies_ms": list(self.latencies_ms),
            "exact_expansion_failures": self.exact_expansion_failures,
            "compressed_tool_errors": self.compressed_tool_errors,
            "oversized_envelopes": self.oversized_envelopes,
            "observed_corruption": self.observed_corruption,
        }


def repository_id_for_path(repository_root: Path) -> str:
    """Hash a real repository root into the opaque ID every receipt and
    manifest slot uses in its place. The path itself is never persisted."""
    resolved = str(repository_root.expanduser().resolve(strict=False))
    return hashlib.sha256(resolved.encode("utf-8")).hexdigest()


def _candidate_wheel_sha256(candidate_wheel_path: Path) -> str:
    try:
        payload = candidate_wheel_path.read_bytes()
    except OSError as error:
        raise ReceiptDerivationError(
            f"candidate wheel is not readable: {candidate_wheel_path}"
        ) from error
    return hashlib.sha256(payload).hexdigest()


def derive_receipt(
    storage: RuntimeStorage,
    *,
    session_id: str,
    manifest: CampaignManifest,
    omp_version: str,
    candidate_wheel_path: Path,
    slot: int,
    repository_root: Path,
    clean_shutdown: bool,
    started_at: float,
    ended_at: float,
    scenarios: tuple[str, ...],
    observed_corruption: int = 0,
) -> SessionReceipt:
    """Derive one privacy-bounded receipt from an existing session ledger.

    Reopens the session's ledger read-through :class:`RuntimeStorage`
    (never a second raw store), re-derives every decision/latency/expansion
    total from `Ledger.runtime_decisions` and `Ledger.runtime_expansion_counts`,
    and independently re-verifies every emitted decision's namespaced
    reference through the same `RuntimeStorage.expand`-equivalent path a
    live `laconic_expand` call would use, rather than trusting the
    write-time check alone.
    """
    if slot < 1:
        raise ReceiptDerivationError(f"slot must be a positive 1-based ordinal: {slot}")
    if ended_at < started_at:
        raise ReceiptDerivationError("ended_at must not precede started_at")
    if observed_corruption < 0:
        raise ReceiptDerivationError(
            f"observed_corruption must not be negative: {observed_corruption}"
        )
    if omp_version != manifest.eligible_omp_version:
        raise ReceiptDerivationError(
            f"session ran OMP {omp_version!r}; the frozen campaign is bound to "
            f"{manifest.eligible_omp_version!r}"
        )
    unknown_scenarios = set(scenarios) - ALL_SCENARIOS
    if unknown_scenarios:
        raise ReceiptDerivationError(f"unknown scenario name(s): {sorted(unknown_scenarios)}")

    repository_id = repository_id_for_path(repository_root)
    candidate_wheel_sha256 = _candidate_wheel_sha256(candidate_wheel_path)
    if candidate_wheel_sha256 != manifest.candidate_wheel_sha256:
        raise ReceiptDerivationError(
            f"candidate wheel {candidate_wheel_path} does not match the frozen "
            f"campaign wheel {manifest.candidate_wheel_sha256!r}"
        )
    expected_repository_id = manifest.repository_id_for_slot(slot)
    if expected_repository_id is None:
        raise ReceiptDerivationError(f"slot {slot} is not declared in the frozen campaign manifest")
    if repository_id != expected_repository_id:
        raise ReceiptDerivationError(
            f"repository at slot {slot} does not match the frozen campaign binding: "
            f"got {repository_id!r}, expected {expected_repository_id!r}"
        )

    with storage.open_existing_ledger(session_id) as ledger:
        decisions = ledger.runtime_decisions()
        full_expansions, span_expansions = ledger.runtime_expansion_counts()

        decisions_total = 0
        eligible_observations = 0
        emitted_count = 0
        raw_chars = 0
        visible_chars = 0
        latencies: list[float] = []
        pass_through: Counter[str] = Counter()
        exact_expansion_failures = 0
        compressed_tool_errors = 0
        oversized_envelopes = 0

        for decision in decisions:
            if decision.reason not in KNOWN_REASONS:
                raise ReceiptDerivationError(
                    f"slot {slot}: decision {decision.sequence} carries a ledger "
                    "reason outside the closed engine vocabulary"
                )
            decisions_total += 1
            raw_chars += decision.raw_chars
            visible_chars += decision.visible_chars
            latencies.append(decision.latency_ms)
            # "Eligible" means Laconic actually attempted compression, matching
            # `laconic.runtime.engine.SessionMetrics`: the engine records a
            # candidate reference for every observation it encoded, and none at
            # all for the two it never evaluates (`unsupported_tool` and
            # `tool_error`). Counting those would let a campaign clear the
            # 100-observation minimum without one real compression candidate.
            if decision.candidate_reference is not None:
                eligible_observations += 1

            if decision.outcome != "emitted":
                pass_through[decision.reason] += 1
                continue

            emitted_count += 1
            # Both counters below re-check the ledger for a row violating an
            # invariant `laconic.runtime.engine` already enforces when writing:
            # a failed tool passes through before the encode path, so no emitted
            # row may carry `tool_error`, and `Ledger.record_runtime_decision`
            # refuses an emitted row whose envelope is not strictly smaller.
            # They therefore detect a tampered or foreign ledger rather than
            # ordinary engine behavior, which is what evidence integrity needs.
            if decision.reason == "tool_error":
                compressed_tool_errors += 1
            if decision.visible_chars >= decision.raw_chars:
                oversized_envelopes += 1
            if decision.candidate_reference is None:
                exact_expansion_failures += 1
                continue
            try:
                reference = RuntimeReference.parse(decision.candidate_reference)
            except InvalidRuntimeReferenceError:
                exact_expansion_failures += 1
                continue
            if reference.session_id != session_id:
                exact_expansion_failures += 1
                continue
            if reference.first_line is not None:
                exact_expansion_failures += 1
                continue
            record = ledger.get(reference.handle)
            if record is None:
                exact_expansion_failures += 1
                continue
            try:
                recovered = ledger.expand(reference.ledger_reference)
            except (UnknownHandleError, InvalidSpanError):
                exact_expansion_failures += 1
                continue
            if recovered != record.raw:
                exact_expansion_failures += 1

    return SessionReceipt(
        schema_version=RECEIPT_SCHEMA_VERSION,
        schema_hash=receipt_schema_fingerprint(),
        manifest_hash=fingerprint_manifest(manifest),
        candidate_wheel_sha256=candidate_wheel_sha256,
        slot=slot,
        repository_id=repository_id,
        clean_shutdown=clean_shutdown,
        started_at=started_at,
        ended_at=ended_at,
        scenarios=tuple(sorted(scenarios)),
        decisions_total=decisions_total,
        eligible_observations=eligible_observations,
        emitted_count=emitted_count,
        pass_through_counts=tuple(sorted(pass_through.items())),
        raw_chars=raw_chars,
        visible_chars=visible_chars,
        characters_avoided=raw_chars - visible_chars,
        full_expansions=full_expansions,
        span_expansions=span_expansions,
        latencies_ms=tuple(latencies),
        exact_expansion_failures=exact_expansion_failures,
        compressed_tool_errors=compressed_tool_errors,
        oversized_envelopes=oversized_envelopes,
        observed_corruption=observed_corruption,
    )


def _require_int(payload: dict[str, Any], key: str) -> int:
    value = payload[key]
    if isinstance(value, bool) or not isinstance(value, int):
        raise ReceiptFormatError(f"{key} must be an int (got {type(value).__name__})")
    return value


def _require_non_negative_int(payload: dict[str, Any], key: str) -> int:
    value = _require_int(payload, key)
    if value < 0:
        raise ReceiptFormatError(f"{key} must not be negative: {value}")
    return value


def _require_number(payload: dict[str, Any], key: str) -> float:
    value = payload[key]
    if isinstance(value, bool) or not isinstance(value, int | float):
        raise ReceiptFormatError(f"{key} must be a number (got {type(value).__name__})")
    return float(value)


def _require_str(payload: dict[str, Any], key: str) -> str:
    value = payload[key]
    if not isinstance(value, str) or not value:
        raise ReceiptFormatError(f"{key} must be a non-empty string")
    return value


def receipt_from_json(payload: dict[str, Any]) -> SessionReceipt:
    """Reconstruct a typed receipt, rejecting anything internally
    inconsistent with :class:`ReceiptFormatError`.

    Callers run `laconic.beta.privacy.validate_receipt_json` first to gate
    the exact key set and enum membership; this function additionally
    checks that the receipt's own numbers add up, which is exactly what a
    hand-edited ("mutated") receipt tends to get wrong.
    """
    schema_version = _require_int(payload, "schema_version")
    schema_hash = _require_str(payload, "schema_hash")
    manifest_hash = _require_str(payload, "manifest_hash")
    candidate_wheel_sha256 = _require_str(payload, "candidate_wheel_sha256")
    slot = _require_int(payload, "slot")
    if slot < 1:
        raise ReceiptFormatError(f"slot must be a positive 1-based ordinal: {slot}")
    repository_id = _require_str(payload, "repository_id")
    clean_shutdown = payload["clean_shutdown"]
    if not isinstance(clean_shutdown, bool):
        raise ReceiptFormatError(
            f"clean_shutdown must be a bool (got {type(clean_shutdown).__name__})"
        )
    started_at = _require_number(payload, "started_at")
    ended_at = _require_number(payload, "ended_at")
    if ended_at < started_at:
        raise ReceiptFormatError("ended_at must not precede started_at")

    scenarios_raw = payload["scenarios"]
    if not isinstance(scenarios_raw, list) or not all(isinstance(s, str) for s in scenarios_raw):
        raise ReceiptFormatError("scenarios must be a list of strings")
    if len(set(scenarios_raw)) != len(scenarios_raw):
        raise ReceiptFormatError("scenarios must not repeat a name")
    unknown_scenarios = set(scenarios_raw) - ALL_SCENARIOS
    if unknown_scenarios:
        raise ReceiptFormatError(
            f"scenarios names {len(unknown_scenarios)} value(s) outside the closed vocabulary"
        )

    decisions_total = _require_non_negative_int(payload, "decisions_total")
    eligible_observations = _require_non_negative_int(payload, "eligible_observations")
    if eligible_observations > decisions_total:
        raise ReceiptFormatError(
            f"eligible_observations cannot exceed decisions_total: "
            f"{eligible_observations} > {decisions_total}"
        )
    emitted_count = _require_non_negative_int(payload, "emitted_count")

    pass_through_raw = payload["pass_through_counts"]
    if not isinstance(pass_through_raw, list):
        raise ReceiptFormatError("pass_through_counts must be a list")
    pass_through_counts: list[tuple[str, int]] = []
    pass_through_total = 0
    for index, entry in enumerate(pass_through_raw):
        if (
            not isinstance(entry, list)
            or len(entry) != 2
            or not isinstance(entry[0], str)
            or isinstance(entry[1], bool)
            or not isinstance(entry[1], int)
        ):
            raise ReceiptFormatError(f"malformed pass_through_counts entry at index {index}")
        reason, count = entry[0], entry[1]
        if reason not in KNOWN_REASONS or count < 0:
            raise ReceiptFormatError(f"malformed pass_through_counts entry at index {index}")
        pass_through_counts.append((reason, count))
        pass_through_total += count
    if len({reason for reason, _ in pass_through_counts}) != len(pass_through_counts):
        raise ReceiptFormatError("pass_through_counts must not repeat a reason")
    if emitted_count + pass_through_total != decisions_total:
        raise ReceiptFormatError(
            "emitted_count plus pass_through_counts must equal decisions_total: "
            f"{emitted_count} + {pass_through_total} != {decisions_total}"
        )
    if emitted_count > eligible_observations:
        raise ReceiptFormatError(
            f"emitted_count cannot exceed eligible_observations: "
            f"{emitted_count} > {eligible_observations}"
        )

    raw_chars = _require_non_negative_int(payload, "raw_chars")
    visible_chars = _require_non_negative_int(payload, "visible_chars")
    characters_avoided = _require_int(payload, "characters_avoided")
    if characters_avoided != raw_chars - visible_chars:
        raise ReceiptFormatError(
            f"characters_avoided must equal raw_chars - visible_chars: "
            f"{characters_avoided} != {raw_chars} - {visible_chars}"
        )

    full_expansions = _require_non_negative_int(payload, "full_expansions")
    span_expansions = _require_non_negative_int(payload, "span_expansions")

    latencies_raw = payload["latencies_ms"]
    if not isinstance(latencies_raw, list):
        raise ReceiptFormatError("latencies_ms must be a list")
    latencies: list[float] = []
    for index, value in enumerate(latencies_raw):
        if isinstance(value, bool) or not isinstance(value, int | float) or value < 0:
            raise ReceiptFormatError(f"malformed latency value at index {index}")
        latencies.append(float(value))
    if len(latencies) != decisions_total:
        raise ReceiptFormatError(
            f"latencies_ms must record exactly one entry per recorded decision: "
            f"{len(latencies)} != {decisions_total}"
        )

    exact_expansion_failures = _require_non_negative_int(payload, "exact_expansion_failures")
    compressed_tool_errors = _require_non_negative_int(payload, "compressed_tool_errors")
    oversized_envelopes = _require_non_negative_int(payload, "oversized_envelopes")
    observed_corruption = _require_non_negative_int(payload, "observed_corruption")
    if exact_expansion_failures > emitted_count:
        raise ReceiptFormatError("exact_expansion_failures cannot exceed emitted_count")
    if compressed_tool_errors > emitted_count or oversized_envelopes > emitted_count:
        raise ReceiptFormatError("a safety counter cannot exceed emitted_count")

    return SessionReceipt(
        schema_version=schema_version,
        schema_hash=schema_hash,
        manifest_hash=manifest_hash,
        candidate_wheel_sha256=candidate_wheel_sha256,
        slot=slot,
        repository_id=repository_id,
        clean_shutdown=clean_shutdown,
        started_at=started_at,
        ended_at=ended_at,
        scenarios=tuple(sorted(scenarios_raw)),
        decisions_total=decisions_total,
        eligible_observations=eligible_observations,
        emitted_count=emitted_count,
        pass_through_counts=tuple(sorted(pass_through_counts)),
        raw_chars=raw_chars,
        visible_chars=visible_chars,
        characters_avoided=characters_avoided,
        full_expansions=full_expansions,
        span_expansions=span_expansions,
        latencies_ms=tuple(latencies),
        exact_expansion_failures=exact_expansion_failures,
        compressed_tool_errors=compressed_tool_errors,
        oversized_envelopes=oversized_envelopes,
        observed_corruption=observed_corruption,
    )
