// laconic-runtime: owned
// Generated by `laconic install omp`; remove with `laconic uninstall omp`.
// Middleware position: Laconic transforms the result produced by handlers
// registered before it and returns only a content override.

import type { ExtensionAPI } from "@oh-my-pi/pi-coding-agent";

export const LACONIC_PYTHON = "__LACONIC_PYTHON__";
export const LACONIC_ENTRYPOINT = ["-m", "laconic.runtime"] as const;
export const LACONIC_DATA_DIRECTORY = "__LACONIC_DATA_DIRECTORY__";

export default function laconicRuntime(pi: ExtensionAPI): void {
  pi.setLabel("Laconic runtime");
}
